### ISSUE TITLE
Why does applyChange require the source parameter?

### ISSUE THREAD

**Issue by mikedmcfarland** [flitbit/diff#45]
In my code I'm maintaining a list of changes, yet not maintaining the source object (as it was when the changes occurred). 

Later, I want to apply the changes to a target, and conceptually see no reason why I'd need to have the source (the changes have all needed information).

Taking a look at applyChange's source, that parameter is seemingly not used.

My 'workaround' is simply just to pass the target again, but I see no reason why this parameter exists in the first place.

**Comment by flitbit** [comment]
Why is an interesting question. Why indeed. 

Looking at my own examples and tests it appears that I was aware of the oddity - some of the examples pass in `true` since the only use of the source tests whether the parameter is truthy.

If I were into speculating I'd say that I intended to allow hooks and observers and such and thought the source data might be meaningful to someone using such... but alas, that kind of thing never got implemented.

As you point out - it appears to be a (nearly) benign artifact of half-baked ideas.
