### ISSUE TITLE
Please provide support for AngularJs apps

### ISSUE THREAD

**Issue by smriti-chawla** [flitbit/diff#50]
I tried using diff in one of my angular apps but it didn't work.

1) I installed using the command "bower install deep-diff --save".
2) I included the script in my index.html - "<script src="bower_components/deep-diff/releases/deep-diff-0.3.1.min.js"></script>"
3) Last I injected it in my app as ['deep-diff']

Console gives an error - "Module 'deep-diff' is not available!"

**Comment by piercers** [comment]
Have you tried DeepDiff?

**Comment by jonathan-reisdorf** [comment]
for me it's working, I use npm and require the module with browserify, works like a charm

**Comment by gpanagakis** [comment]
check out this plunk : http://plnkr.co/edit/dIVOcs  
here I tried to integrate as an angular module.

Or you can simply use  DeepDiff  directly inside your angular controllers after including
the deep-diff script in your index.html. DeepDiff is attached to the global scope and can be used
as is in angular ,but is not a good practise since you may have global scope name collisions.
   Example use:

vas app = angular.module('myApp', []);
app.controller('MainCtrl', function($scope) {
  var difference = DeepDiff.diff(obj1, obj2);
});

**Comment by alberto-bottarini** [comment]
Definition of service:

```
(function (name) {
    'use strict';

    angular.module('myapp.shared').service(name, service);

    function service() { 
        return function (left, right) {
            return DeepDiff.diff(left, right);
        };
    }

})('MyDeepDiffService');
```

Usage:
```
(function (name) {
    'use strict';

    angular.module('myapp.controller').controller(name, controller);

    controller.$inject = [ 'MyDeepDiffService' ];
    function controller(MyDeepDiffService) { 
       .....
    }

})('MyController');
```

**Comment by flitbit** [comment]
No issues here - see the thread. Can be imported in a script tag. Has a `.noConflict` feature.
