### ISSUE TITLE
how would I go about observing changes to an object over time asyncronously? 

### ISSUE THREAD

**Issue by faceyspacey** [flitbit/diff#57]
e.g. the equivalent of `observableDiff` without the target object:

```
observeObject(rhs, function (d) {
   applyChange(lhs, rhs, d);
});
```

**Comment by flitbit** [comment]
That's a tricky prospect &mdash; increasingly so with the introduction of new language features such as [Symbols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol).

When it comes down to it, you are talking about _observing_ all externally visible changes in the target object's state. Such a mechanism would have to _hook_ every visible property on the target object (getters, setters, fields, methods) and compare _pre_ and _post_ states. Such would probably fire _events_ based on observed state changes. It isn't an easy problem, and in order to be reliable the target object must be open to monkey patching (meaning _configurable_ and _writable_ for most properties).

IMHO: within your own system, where you are the author of all observed objects/classes, it can be a reasonable pursuit. But if you mean to reliably observe the state transitions of objects authored by others, you will find yourself in a quagmire of customized handlers, filters, etc.

The complexity and attendant problems in the face of change (e.g. difficult to future proof) is what lead me to implement `deep-diff` in the first place. I take a less aggressive approach using `deep-diff` to periodically _synchronizing_ what I know about the changing state rather than attempting to reliably _observe_ it. 

BTW: I would love for someone, probably much smarter than myself, to prove my opinion on the matter wrong by building a precise, general purpose, performant _object-state observer module_ for javascript.
